# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/uart0_gpio.xdc

# Block Designs: bd/ultra96_fpga/ultra96_fpga.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga || ORIG_REF_NAME==ultra96_fpga} -quiet] -quiet

# IP: bd/ultra96_fpga/ip/ultra96_fpga_zynq_ultra_ps_e_0_0/ultra96_fpga_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ultra96_fpga_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ultra96_fpga/ip/ultra96_fpga_axi_gpio_0_0/ultra96_fpga_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga_axi_gpio_0_0 || ORIG_REF_NAME==ultra96_fpga_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ultra96_fpga/ip/ultra96_fpga_xbar_0/ultra96_fpga_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga_xbar_0 || ORIG_REF_NAME==ultra96_fpga_xbar_0} -quiet] -quiet

# IP: bd/ultra96_fpga/ip/ultra96_fpga_auto_ds_0/ultra96_fpga_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga_auto_ds_0 || ORIG_REF_NAME==ultra96_fpga_auto_ds_0} -quiet] -quiet

# IP: bd/ultra96_fpga/ip/ultra96_fpga_auto_pc_0/ultra96_fpga_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga_auto_pc_0 || ORIG_REF_NAME==ultra96_fpga_auto_pc_0} -quiet] -quiet

# IP: bd/ultra96_fpga/ip/ultra96_fpga_auto_ds_1/ultra96_fpga_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga_auto_ds_1 || ORIG_REF_NAME==ultra96_fpga_auto_ds_1} -quiet] -quiet

# IP: bd/ultra96_fpga/ip/ultra96_fpga_auto_pc_1/ultra96_fpga_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga_auto_pc_1 || ORIG_REF_NAME==ultra96_fpga_auto_pc_1} -quiet] -quiet

# IP: bd/ultra96_fpga/ip/ultra96_fpga_ps8_0_axi_periph_0/ultra96_fpga_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga_ps8_0_axi_periph_0 || ORIG_REF_NAME==ultra96_fpga_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/ultra96_fpga/ip/ultra96_fpga_rst_ps8_0_100M_0/ultra96_fpga_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ultra96_fpga_rst_ps8_0_100M_0 || ORIG_REF_NAME==ultra96_fpga_rst_ps8_0_100M_0} -quiet] -quiet

# XDC: /home/ksksho/vitis/Ubuntu-Ultra96/fpga/ultra96/ultra96.gen/sources_1/bd/ultra96_fpga/ultra96_fpga_ooc.xdc
