# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ksksho/vitis/Ubuntu-Ultra96/fpga/ultra96/ultra96.srcs/sources_1/bd/ultra96_fpga/ip/ultra96_fpga_rst_ps8_0_100M_0/ultra96_fpga_rst_ps8_0_100M_0.xci
# IP: The module: 'ultra96_fpga_rst_ps8_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ksksho/vitis/Ubuntu-Ultra96/fpga/ultra96/ultra96.gen/sources_1/bd/ultra96_fpga/ip/ultra96_fpga_rst_ps8_0_100M_0/ultra96_fpga_rst_ps8_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96_fpga_rst_ps8_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ksksho/vitis/Ubuntu-Ultra96/fpga/ultra96/ultra96.gen/sources_1/bd/ultra96_fpga/ip/ultra96_fpga_rst_ps8_0_100M_0/ultra96_fpga_rst_ps8_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96_fpga_rst_ps8_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ksksho/vitis/Ubuntu-Ultra96/fpga/ultra96/ultra96.gen/sources_1/bd/ultra96_fpga/ip/ultra96_fpga_rst_ps8_0_100M_0/ultra96_fpga_rst_ps8_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96_fpga_rst_ps8_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ksksho/vitis/Ubuntu-Ultra96/fpga/ultra96/ultra96.srcs/sources_1/bd/ultra96_fpga/ip/ultra96_fpga_rst_ps8_0_100M_0/ultra96_fpga_rst_ps8_0_100M_0.xci
# IP: The module: 'ultra96_fpga_rst_ps8_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ksksho/vitis/Ubuntu-Ultra96/fpga/ultra96/ultra96.gen/sources_1/bd/ultra96_fpga/ip/ultra96_fpga_rst_ps8_0_100M_0/ultra96_fpga_rst_ps8_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96_fpga_rst_ps8_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ksksho/vitis/Ubuntu-Ultra96/fpga/ultra96/ultra96.gen/sources_1/bd/ultra96_fpga/ip/ultra96_fpga_rst_ps8_0_100M_0/ultra96_fpga_rst_ps8_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96_fpga_rst_ps8_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ksksho/vitis/Ubuntu-Ultra96/fpga/ultra96/ultra96.gen/sources_1/bd/ultra96_fpga/ip/ultra96_fpga_rst_ps8_0_100M_0/ultra96_fpga_rst_ps8_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96_fpga_rst_ps8_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
